v: 2.6.0
overrideConfig: false
ie:
  - DS_Store
  - less
  - scss
id:
  - scss
  - .svn
  - .sass-cache
cleanPublic: 'true'
patternStates:
  - inprogress
  - inreview
  - complete
styleGuideExcludes: ''
cacheBusterOn: 'true'
exportDir: export
publicDir: public
sourceDir: ../source
defaultPattern: all
defaultShowPatternInfo: false
ishMinimum: '240'
ishMaximum: '2600'
ishControlsHide:
  - hay
lineageMatch: >-
  {%([ ]+)?include(
  |\()[&quot;\&#039;]([A-Za-z0-9-_]+)[&quot;\&#039;](\))?(.*)%}
lineageMatchKey: 3
patternExtension: twig
twigDebug: true
twigAutoescape: false
twigDefaultDateFormat: ''
twigDefaultIntervalFormat: ''
twigMacroExt: macro.twig
twigFilterExt: filter.php
twigFunctionExt: function.php
twigTagExt: tag.php
twigTestExt: test.php
styleguideKit: pattern-lab/styleguidekit-twig-default
styleguideKitPath: vendor/pattern-lab/styleguidekit-twig-default
plugins:
  dataInheritance:
    enabled: true
  faker:
    enabled: true
    locale: it_IT
  twigNamespaces:
    enabled: true
    namespaces:
      base:
        paths:
          - ../source/_patterns/00-base
          - ../source/_patterns/00-base/00-settings
          - ../source/_patterns/00-base/02-generic
          - ../source/_patterns/00-base/02-generic/layout
      atoms:
        paths:
          - ../source/_patterns/01-atoms
          - ../source/_patterns/01-atoms/00-branding/01-colors
          - ../source/_patterns/01-atoms/00-branding/02-fonts
          - ../source/_patterns/01-atoms/00-branding/favicon
          - ../source/_patterns/01-atoms/01-typography/00-headings/heading-1
          - ../source/_patterns/01-atoms/01-typography/00-headings/heading-2
          - ../source/_patterns/01-atoms/01-typography/00-headings
          - ../source/_patterns/01-atoms/01-typography/01-text
          - ../source/_patterns/01-atoms/01-typography/02-lists
          - ../source/_patterns/01-atoms/02-buttons
          - ../source/_patterns/01-atoms/03-images
          - ../source/_patterns/01-atoms/03-images/landscape-3x2
          - ../source/_patterns/01-atoms/04-video
          - ../source/_patterns/01-atoms/05-form-elements/checkbox
          - ../source/_patterns/01-atoms/05-form-elements/input
          - ../source/_patterns/01-atoms/05-form-elements/label
          - ../source/_patterns/01-atoms/05-form-elements/radio
          - ../source/_patterns/01-atoms/05-form-elements/select
          - ../source/_patterns/01-atoms/05-form-elements/textarea
          - ../source/_patterns/01-atoms/06-tables
      molecules:
        paths:
          - ../source/_patterns/02-molecules
          - ../source/_patterns/02-molecules/00-containers/blocks
          - ../source/_patterns/02-molecules/00-containers/regions
          - ../source/_patterns/02-molecules/01-fields
          - ../source/_patterns/02-molecules/02-contents/accordion-item
          - ../source/_patterns/02-molecules/02-contents/branding
          - ../source/_patterns/02-molecules/02-contents
          - ../source/_patterns/02-molecules/02-contents/card
          - ../source/_patterns/02-molecules/02-contents/code
          - ../source/_patterns/02-molecules/02-contents/cover
          - ../source/_patterns/02-molecules/02-contents/footer--legal
          - ../source/_patterns/02-molecules/02-contents/metadata
          - ../source/_patterns/02-molecules/02-contents/shila-image
          - ../source/_patterns/02-molecules/03-navigation/breadcrumbs
          - ../source/_patterns/02-molecules/03-navigation/menu-trigger
          - ../source/_patterns/02-molecules/03-navigation/menu
          - ../source/_patterns/02-molecules/03-navigation/pager
          - ../source/_patterns/02-molecules/03-navigation/tabs
          - ../source/_patterns/02-molecules/04-forms
      organisms:
        paths:
          - ../source/_patterns/03-organisms
          - ../source/_patterns/03-organisms/grid-cards
          - ../source/_patterns/03-organisms/side-menu
          - ../source/_patterns/03-organisms/site-footer
          - ../source/_patterns/03-organisms/site-header
      templates:
        paths:
          - ../source/_patterns/04-templates
          - ../source/_patterns/04-templates/content-types
      pages:
        paths:
          - ../source/_patterns/05-pages
