v: 2.6.0
overrideConfig: false
ie:
  - DS_Store
  - less
  - scss
id:
  - scss
  - .svn
  - .sass-cache
cleanPublic: 'true'
patternStates:
  - inprogress
  - inreview
  - complete
styleGuideExcludes: ''
cacheBusterOn: 'true'
exportDir: export
publicDir: public
sourceDir: ../source
defaultPattern: all
defaultShowPatternInfo: false
ishMinimum: '240'
ishMaximum: '2600'
ishControlsHide:
  - hay
lineageMatch: >-
  {%([ ]+)?include(
  |\()[&quot;\&#039;]([A-Za-z0-9-_]+)[&quot;\&#039;](\))?(.*)%}
lineageMatchKey: 3
patternExtension: twig
twigDebug: true
twigAutoescape: false
twigDefaultDateFormat: ''
twigDefaultIntervalFormat: ''
twigMacroExt: macro.twig
twigFilterExt: filter.php
twigFunctionExt: function.php
twigTagExt: tag.php
twigTestExt: test.php
styleguideKit: pattern-lab/styleguidekit-twig-default
styleguideKitPath: vendor/pattern-lab/styleguidekit-twig-default
plugins:
  faker:
    enabled: true
    locale: en_US
  twigNamespaces:
    enabled: true
    namespaces:
      base:
        paths:
          - ../source/_patterns/00-base
          - ../source/_patterns/00-base/00-settings
          - ../source/_patterns/00-base/02-generic/layout
      atoms:
        paths:
          - ../source/_patterns/01-atoms
          - ../source/_patterns/01-atoms/00-branding/01-colors
          - ../source/_patterns/01-atoms/00-branding/02-fonts
          - ../source/_patterns/01-atoms/02-typography/00-headings
          - ../source/_patterns/01-atoms/02-typography/01-text
          - ../source/_patterns/01-atoms/02-typography/02-lists
          - ../source/_patterns/01-atoms/03-buttons
          - ../source/_patterns/01-atoms/04-images
      molecules:
        paths:
          - ../source/_patterns/02-molecules
          - ../source/_patterns/02-molecules/branding
          - ../source/_patterns/02-molecules/caption-block
      organisms:
        paths:
          - ../source/_patterns/03-organisms
          - ../source/_patterns/03-organisms/grids/caption-grid-block
          - ../source/_patterns/03-organisms/site/site-footer
          - ../source/_patterns/03-organisms/site/site-header
      templates:
        paths:
          - ../source/_patterns/04-templates
          - ../source/_patterns/04-templates/content-types
      pages:
        paths:
          - ../source/_patterns/05-pages
